version: '2.1'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: app:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - storage-databases:/app/storage/databases
      - storage-app:/app/storage/app
    networks:
      - app
    env_file: .env


volumes:
  storage-databases:
  storage-app:

networks:
  app:
    driver: bridge
